title: JThelin.GitHub.io
description: JThelin @ GitHub
show_downloads: false
theme: jekyll-theme-hacker

plugins:
  - jekyll-mentions

exclude: [
  "*_keys.yaml",
  "*tweets.csv",
  "*README.md",
  "*README.txt",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/"
]
